### ISSUE TITLE
Questions about the 'mean_ap' function

### ISSUE THREAD

**Issue by cppcute-pm** [chen960/CA-Jaccard#2]
Hello, chenyiyuu! It's really a nice work you've done to the person Re-ID community.

I'm a new one to this community and I have a question about code related to 'mean_ap' function. Why you need to sort the distmat to finally get the y_true and y_score? I think this operation would get y_true and y_score sorted in an ascending order of the feature distance, but the sklearn's official guide doesn't mention that the average_precision_score's input should be some kind of sorted. By the way, the examples show that the y_true is sorted in an ascending order, not the y_score.

Could you explain this part of code carefully? Thanks!

**Comment by chenyiyuu** [comment]
The mean_ap function is used to calculate the mAP accuracy in the person re-identification task. The calculation rule of this mAP is different from that of other tasks. Person re-identification is an image retrieval task. The goal is to make images belonging to the same person as far as possible in the ranking list. mean_ap needs to calculate the rank of inter-camera samples with the same identity in the ranking list. The calculation rule of precision is the i-th positive sample divided by its rank in the ranking list. You can search the definition of mAP in re-ID, then you will understand the code.
